<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MUIS24O" failures="1" tests="3" name="Test" time="30.279" errors="0" timestamp="2020-09-16T14:46:32 CEST">
  <testcase classname="authenticationTests.AuthenticationForm" name="sucessAuthentication" time="1.226">
    <failure type="java.lang.AssertionError" message="The text does not match the expected secure message expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The text does not match the expected secure message expected [true] but found [false]
at authenticationTests.AuthenticationForm.sucessAuthentication(AuthenticationForm.java:25)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- sucessAuthentication -->
  <testcase classname="authenticationTests.AuthenticationForm" name="failedAuthentication" time="1.23"/>
  <testcase classname="authenticationTests.AuthenticationForm" name="incorrectPasswordAuth" time="1.226"/>
</testsuite> <!-- Test -->
